name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging server
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key root@64.227.148.39 << 'EOF'
            export PNPM="/root/.nvm/versions/node/v22.15.0/bin/pnpm"
            export PM2="/root/.nvm/versions/node/v22.15.0/bin/pm2"

            cd monorepoDeploy
            git pull
            $PNPM install
            $PNPM run build

            # Start if not already running, otherwise restart
            $PM2 start apps/web/server.js --name next-server || $PM2 restart next-server
            $PM2 start apps/http/server.js --name http-server || $PM2 restart http-server
            $PM2 start apps/ws/server.js --name ws-server || $PM2 restart ws-server

            $PM2 save  # Save the PM2 process list so they persist after reboot
          EOF
